# Generated by Django 3.1.2 on 2020-11-25 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TwitterAccount',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('screen_name', models.TextField()),
                ('created_date', models.DateField()),
                ('follower_num', models.IntegerField()),
            ],
        ),
    ]
