# Generated by Django 3.1.2 on 2021-01-03 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='twitteraccount',
            name='followers',
            field=models.ManyToManyField(related_name='following', to='website.TwitterAccount'),
        ),
    ]
