# Generated by Django 3.1.2 on 2021-03-01 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0003_auto_20210215_2033'),
    ]

    operations = [
        # migrations.AddField(
        #     model_name='twitteraccount',
        #     name='following',
        #     field=models.ManyToManyField(blank=True, null=True, related_name='followed', to='website.TwitterAccount'),
        # ),
        migrations.AlterField(
            model_name='twitteraccount',
            name='created_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='twitteraccount',
            name='follower_num',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='twitteraccount',
            name='followers',
            field=models.ManyToManyField(blank=True, null=True, related_name='follows', to='website.TwitterAccount'),
        ),
        migrations.AlterField(
            model_name='twitteraccount',
            name='following_num',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='twitteraccount',
            name='protected',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='twitteraccount',
            name='screen_name',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='twitteraccount',
            name='suspended',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AlterField(
            model_name='twitteraccount',
            name='id',
            field=models.CharField(max_length = 100, primary_key=True, serialize=False),
        ),
    ]
