# Generated by Django 3.1.2 on 2021-03-02 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0004_auto_20210301_1936'),
    ]

    operations = [
        # migrations.RemoveField(
        #     model_name='twitteraccount',
        #     name='twitter_id',
        # ),
        # migrations.AddField(
        #     model_name='twitteraccount',
        #     name='following',
        #     field=models.ManyToManyField(blank=True, related_name='followed', to='website.TwitterAccount'),
        # ),
        migrations.AlterField(
            model_name='twitteraccount',
            name='followers',
            field=models.ManyToManyField(blank=True, related_name='follows', to='website.TwitterAccount'),
        ),
    ]
