# Generated by Django 3.1.2 on 2021-03-02 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0005_auto_20210302_1736'),
    ]

    # operations = [
    #     migrations.AddField(
    #         model_name='twitteraccount',
    #         name='following',
    #         field=models.ManyToManyField(blank=True, related_name='followed', to='website.TwitterAccount'),
    #     ),
    # ]
