# Generated by Django 3.1.2 on 2021-03-02 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0006_twitteraccount_following'),
    ]

    operations = [
        migrations.AlterField(
            model_name='twitteraccount',
            name='id',
            field=models.CharField(max_length=25, primary_key=True, serialize=False),
        ),
    ]
