# Generated by Django 3.1.2 on 2021-03-07 02:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0008_remove_twitteraccount_twitter_id'),
    ]

    operations = [
        migrations.RemoveField(
           model_name='twitteraccount',
           name='twitter_id',
        ),
        migrations.AlterField(
            model_name='twitteraccount',
            name='followers',
            field=models.ManyToManyField(blank=True, related_name='following', to='website.TwitterAccount'),
        ),
    ]
