# Generated by Django 3.1.2 on 2021-03-07 03:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0009_auto_20210307_0220'),
    ]

    operations = [
        migrations.AlterField(
            model_name='twitteraccount',
            name='id',
            field=models.CharField(max_length=64, primary_key=True, serialize=False),
        ),
    ]
